Battleships/Pages/GameBattle.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Battleships.Models;
using Battleships.Models.Enums;
using Battleships.Services;
using Battleships.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Utf8Json;

namespace Battleships.Pages
{
    public class GamesListModel : PageModel //Barth
    {
        private IGame _gameService;
        private SessionStorage<Guid> _sessionGuid;
        public Game Game;
        public Guid _gameId;
        public int _gameSize;
        public BattlefieldPartialModel partialModel;
        public List<List<NavyBattlePiece>> PlayingField;
        public List<BattlefieldPartialModel> partialModels { get; set; } = new List<BattlefieldPartialModel>();


        public GamesListModel(IGame game, SessionStorage<Guid> sessionGuid)
        {
            _gameService = game;
            _sessionGuid = sessionGuid;
            _gameId = sessionGuid.Load("GameId");
            Game = _gameService.GetGame(_gameId);

            
        }

        public void OnGet()
        {
            
            foreach (var item in Game.UserGames)
            {
                partialModels.Add(new BattlefieldPartialModel(_gameService.GetBattlefield(item.NavyBattlePieces.OrderBy(x => x.PosX).ToList()), item, _gameService.GetUser()));
            }
            
            Game = _gameService.GetGame(_gameId);
            _gameService.ChangeGameState(Game.GameId);
        }



        public ActionResult OnGetPieceClick(int x, int y, int ug)
        {
            _gameService.PlaceShip(ug, x, y);
            Game = _gameService.GetGame(_gameId);
            partialModels.Clear();
            foreach (var item in Game.UserGames)
            {
                partialModels.Add(new BattlefieldPartialModel(_gameService.GetBattlefield(item.NavyBattlePieces.OrderBy(x => x.PosX).ToList()), item, _gameService.GetUser()));
            }

            return Page();
        }
    }
}

Battleships/Pages/Shared/_Battlefield.cshtml
@using ViewModels
@using Microsoft.EntityFrameworkCore;
@model BattlefieldPartialModel



@{

    <table class="bftable">
        @foreach (var item in Model.Battlefield)
        {
            <tr>

                @foreach (var item2 in item)
                {
                    if (item2.Hidden != true || Model.UserGame.User == Model.LoggedInUser)
                    {
                        if (item2.PieceState == Models.Enums.PieceState.Water)
                        {
                            <td class="bftd bg-primary" style="color: white">
                                <a asp-page-handler="PieceClick" asp-route-x="@item2.PosX" asp-route-y="@item2.PosY" asp-route-ug="@Model.UserGame.Id"><div style="width: 100%; height: 100%">@item2.PosX-@item2.PosY</div></a>
                            </td>

                        }
                        if (item2.PieceState == Models.Enums.PieceState.Ship)
                        {
                            <td class="bftd bg-dark" style="color: white">
                                <a asp-page-handler="PieceClick" asp-route-x="@item2.PosX" asp-route-y="@item2.PosY" asp-route-ug="@Model.UserGame.Id"><div style="width: 100%; height: 100%">@item2.PosX-@item2.PosY</div></a>
                            </td>
                        }
                        if (item2.PieceState == Models.Enums.PieceState.DeadShip)
                        {
                            <td class="bftd bg-danger" style="color: white">
                                <a asp-page-handler="PieceClick" asp-route-x="@item2.PosX" asp-route-y="@item2.PosY" asp-route-ug="@Model.UserGame.Id"><div style="width: 100%; height: 100%">@item2.PosX-@item2.PosY</div></a>
                            </td>
                        }
                        if (item2.PieceState == Models.Enums.PieceState.DeadWater)
                        {
                            <td class="bftd bg-light" style="color: white">
                                <a asp-page-handler="PieceClick" asp-route-x="@item2.PosX" asp-route-y="@item2.PosY" asp-route-ug="@Model.UserGame.Id"><div style="width: 100%; height: 100%">@item2.PosX-@item2.PosY</div></a>
                            </td>
                        }
                    }
                    else
                    {
                        <td class="bftd">
                            <a asp-page-handler="PieceClick" asp-route-x="@item2.PosX" asp-route-y="@item2.PosY" asp-route-ug="@Model.UserGame.Id"><div style="width: 100%; height: 100%">@item2.PosX-@item2.PosY</div></a>
                        </td>
                    }

                }
            </tr>
        }
    </table>

}

Battleships/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Battleships</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Battleships</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    @*<ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>*@
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Battleships - Petr Horák,  Michal Barth,  Miroslav Maděra 
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>