Battleships/Models/Game.cs
using Battleships.Models.Enums;
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Battleships.Models
{
    public class Game
    {
        [Key]
        public Guid GameId { get; set; }

        public int MaxPlayers { get; set; }
        public int GameSize { get; set; }

        // co to znamená?
        public string CurrentPlayerId { get; set; }

        public string OwnerId { get; set; }
        
        [ForeignKey("OwnerId")]
        public User User { get; set; }

        public ICollection<UserGame> UserGames { get; set; }
        public GameState GameState { get; set; }
    }
}

Battleships/Pages/Game.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Battleships.Models;
using Battleships.Models.Enums;
using Battleships.Services;
using Battleships.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Battleships.Pages
{
    public class GameModel : PageModel  //Autor: Petr Horák
    {
        private IGame _gameService;
        private SessionStorage<Guid> _sessionGuid;
        public Game Game;
        public Guid _gameId;
        public int _gameSize;
        public BattlefieldPartialModel partialModel;
        public List<List<NavyBattlePiece>> PlayingField;
        

        public GameModel(IGame game, SessionStorage<Guid> sessionGuid)
        {           
            _gameService = game;
            _sessionGuid = sessionGuid;            
            _gameId = sessionGuid.Load("GameId");
            Game = _gameService.GetGame(_gameId);
        }

        //public void OnGet()
        //{
        //    partialModel = new BattlefieldPartialModel(_gameService.GetBattlefield(_gameId), _gameService.GetGame(_gameId), _gameService);
        //    Game = _gameService.GetGame(_gameId);
        //}

        //public ActionResult OnGetPieceClick(int x, int y, int ug)
        //{
        //    partialModel = new BattlefieldPartialModel(_gameService.GetBattlefield(_gameId), _gameService.GetGame(_gameId), _gameService);
        //    Game = _gameService.GetGame(_gameId);
        //    _gameService.PlaceShip(ug, x, y);
            
        //    return Page();
        //}

        //public ActionResult OnGetDone()
        //{
        //    partialModel = new BattlefieldPartialModel(_gameService.GetBattlefield(_gameId), _gameService.GetGame(_gameId), _gameService);
        //    Game = _gameService.GetGame(_gameId);
        //    _gameService.ChangePlayerState(_gameService.GetUserGame(Game.GameId), PlayerState.Playing);
        //    _gameService.ChangeGameState(Game.GameId);
        //    return Page();
        //}

        //public ActionResult OnGetFire()
        //{
        //    partialModel = new BattlefieldPartialModel(_gameService.GetBattlefield(_gameId), _gameService.GetGame(_gameId), _gameService);
        //    Game = _gameService.GetGame(_gameId);

        //    //TODO

        //    return Page();
        //}
    }
}

Battleships/Pages/GameBattle.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Battleships.Models;
using Battleships.Models.Enums;
using Battleships.Services;
using Battleships.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Utf8Json;

namespace Battleships.Pages
{
    public class GamesListModel : PageModel //Barth
    {
        private IGame _gameService;
        private SessionStorage<Guid> _sessionGuid;
        public Game Game;
        public Guid _gameId;
        public int _gameSize;
        public BattlefieldPartialModel partialModel;
        public List<List<NavyBattlePiece>> PlayingField;
        public List<BattlefieldPartialModel> partialModels { get; set; } = new List<BattlefieldPartialModel>();


        public GamesListModel(IGame game, SessionStorage<Guid> sessionGuid)
        {
            _gameService = game;
            _sessionGuid = sessionGuid;
            _gameId = sessionGuid.Load("GameId");
            Game = _gameService.GetGame(_gameId);

            
        }

        public void OnGet()
        {
            
            foreach (var item in Game.UserGames)
            {
                partialModels.Add(new BattlefieldPartialModel(_gameService.GetBattlefield(item.NavyBattlePieces.OrderBy(x => x.PosX).ToList()), item, _gameService.GetUser()));
            }
            
            Game = _gameService.GetGame(_gameId);
            _gameService.ChangeGameState(Game.GameId);
        }



        public ActionResult OnGetPieceClick(int x, int y, int ug)
        {
            _gameService.PlaceShip(ug, x, y);
            Game = _gameService.GetGame(_gameId);
            partialModels.Clear();
            foreach (var item in Game.UserGames)
            {
                partialModels.Add(new BattlefieldPartialModel(_gameService.GetBattlefield(item.NavyBattlePieces.OrderBy(x => x.PosX).ToList()), item, _gameService.GetUser()));
            }

            return Page();
        }
    }
}

Battleships/Pages/GamePreparation.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Battleships.Services;
using Battleships.Models;
using Battleships.ViewModels;
using Battleships.Models.Enums;

namespace Battleships.Pages
{
    public class GamePreparationModel : PageModel 
    {
        private IGame _gameService;
        private SessionStorage<Guid> _sessionGuid;
        public Game Game;
        public Guid _gameId;
        public int _gameSize;
        public BattlefieldPartialModel partialModel;
        public List<List<NavyBattlePiece>> PlayingField;


        public GamePreparationModel(IGame game, SessionStorage<Guid> sessionGuid)
        {
            _gameService = game;
            _sessionGuid = sessionGuid;
            _gameId = sessionGuid.Load("GameId");
            Game = _gameService.GetGame(_gameId);
        }

        public void OnGet()
        {
            partialModel = new BattlefieldPartialModel(_gameService.GetBattlefield(_gameService.GetUserGame(_gameId).NavyBattlePieces.OrderBy(x => x.PosX).ToList()), _gameService.GetUserGame(_gameId), _gameService.GetUser());
            Game = _gameService.GetGame(_gameId);
        }

        public ActionResult OnGetPieceClick(int x, int y, int ug)
        {
            partialModel = new BattlefieldPartialModel(_gameService.GetBattlefield(_gameService.GetUserGame(_gameId).NavyBattlePieces.OrderBy(x => x.PosX).ToList()), _gameService.GetUserGame(_gameId), _gameService.GetUser());
            Game = _gameService.GetGame(_gameId);
            _gameService.PlaceShip(ug, x, y);

            return Page();
        }

        public ActionResult OnGetDone()
        {
            partialModel = new BattlefieldPartialModel(_gameService.GetBattlefield(_gameService.GetUserGame(_gameId).NavyBattlePieces.OrderBy(x => x.PosX).ToList()), _gameService.GetUserGame(_gameId), _gameService.GetUser());
            Game = _gameService.GetGame(_gameId);
            _gameService.ChangePlayerState(_gameService.GetUserGame(Game.GameId), PlayerState.Playing);
            _gameService.ChangeGameState(Game.GameId);
            return RedirectToPage("./GameBattle");
        }
    }
}

Battleships/Pages/GamesListPH.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Battleships.Models;
using Battleships.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Battleships.Pages
{
    public class PrivacyModel : PageModel
    {
        private SessionStorage<Guid> _session;
        
        public List<Game> AllGames;
        public List<Game> ActiveGames;
        private IGamePreparation _gp;
        private IMainMenu _mm;
        public IGame _ga;

        [TempData]
        public string MessageSuccess { get; set; }
        [TempData]
        public string MessageError { get; set; }


        public PrivacyModel(SessionStorage<Guid> session, IGamePreparation gp, IGame ga, IMainMenu mm)
        {
            _session = session;
            _gp = gp;
            _ga = ga;
            _mm = mm;
        }

        public void OnGet()
        {
            AllGames = _gp.LoadAllGames();
            ActiveGames = _gp.LoadActiveGames();
        }

        public ActionResult OnGetRemoveGame(Guid value)
        {
            _mm.DeleteGame(value);
            AllGames = _gp.LoadAllGames();
            ActiveGames = _gp.LoadActiveGames();

            MessageSuccess += "success";
            return Page();
        }

        public ActionResult OnGetEnterGame(Guid value)
        {
            
            _ga.JoinGame(value);
            
            return RedirectToPage("./GamePreparation");
        }
    }
}

Battleships/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Battleships.Services;

namespace Battleships.Pages
{
    public class IndexModel : PageModel //Barth, Horák(session - rozměry hracího pole do sessiony pro redirect na GamePrep.)
    {
        
        private IGamePreparation _g;
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger, IGamePreparation g)
        {
            _logger = logger;
            _g = g;
            
        }

        public void OnGet()
        {
            
        }

        public ActionResult OnGetStartGame(int size)
        {
            _g.StartGame(size);
            
            return RedirectToPage("./GamePreparation");
        }
    }
}

Battleships/Pages/Game.cshtml
@page
@model Battleships.Pages.GameModel
@{
    ViewData["Title"] = "Game";
}


<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <img src="~/images/logo.png" alt="Alternate Text" class="center" />
    <h1 class="text-center">Game</h1>
    <div class="alert alert-light text-center" role="alert">
        Výpis z DB: (předělat do PartialView - upravit - přidat na ostatní stránky)
    </div>
    
    
    <partial name="_Battlefield" model="Model.partialModel" />
    
    
    
    
    @*<table>
        @foreach (var item in Model.PlayingField)
        {
            <tr>
                @foreach (var item2 in item)
                {
                <td>@item2.PosX - @item2.PosY</td>
                }               
            </tr>
        }
    </table>*@
</body>
</html>

Battleships/Pages/GameBattle.cshtml
@page
@model Battleships.Pages.GamesListModel
@{
    ViewData["Title"] = "GamesList";
}

    @{  
        if (Model.Game.GameState == Battleships.Models.Enums.GameState.Setup)
        {
            <h2 class="text-center">Waiting for the other player to join...</h2>
            <h4 class="text-center">Refresh the page</h4>
        }
        else if (Model.Game.GameState == Battleships.Models.Enums.GameState.Battle)
        {
            foreach (var pmodel in Model.partialModels)
            {
                if (pmodel.UserGame.PlayerState == Models.Enums.PlayerState.Playing)
                {
                    <h6>@pmodel.UserGame.User.UserName</h6>

                    <partial name="_Battlefield" model="pmodel" />
                }
            }
        }
    }

Battleships/Pages/GamePreparation.cshtml
@page
@model Battleships.Pages.GamePreparationModel
@{
    ViewData["Title"] = "GamePreparation";
}

<img src="~/images/logo.png" alt="Alternate Text" class="center" />



    @if (Model.Game.GameState == Battleships.Models.Enums.GameState.Setup)
    {



        <h5 class="text-center">Place your ships</h5>


        <partial name="_Battlefield" model="Model.partialModel" />

        if (Model.partialModel.UserGame.PlayerState != Models.Enums.PlayerState.Playing)
        {
            <div class="text-center">
                <a class="btn btn-primary" asp-page="Index">Cancel</a>
                <a class="btn btn-primary" asp-page-handler="Done">Done</a>
            </div>
        }

    }

Battleships/Pages/GamesListPH.cshtml
@page
@model PrivacyModel
@{
    ViewData["Title"] = "Games List";
}

@if (Model.MessageSuccess?.Length > 0)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">Game removed successfully.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
}
@if (Model.MessageError?.Length > 0)
{
    <div class="alert alert-warning alert-dismissible fade show" role="alert">Error occured.<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
}

<img src="~/images/logo.png" alt="Alternate Text" class="center" />
<p class="text-center game-list-title">Your listed games, feel free to choose.</p>
<table class="table table-striped table-hover game-list-table">
    <tr class="head">
        <td>Owner:</td>
        <td>Game State</td>
        <td>Game Size</td>
        <td>Join Game</td>
        <td>Remove Game</td>
    </tr>

    @foreach (var item in Model.AllGames)
    {
        <tr>
            <td>@Model._ga.GetUserName(item.OwnerId)</td>
            <td>@item.GameState</td>
            <td>@item.GameSize</td>

            <td><a class="btn btn-primary" asp-page-handler="EnterGame" asp-route-value="@item.GameId">Join</a></td>
            <td><a class="btn btn-danger" asp-page-handler="RemoveGame" asp-route-value="@item.GameId">Remove</a></td>
        </tr>
    }
</table>

@*<div class="alert alert-light text-center" role="alert">
        Games you :
    </div>

    <table class="table table-info">
        @foreach (var item in Model.ActiveGames)
        {
            <tr>
                <td><i>@item.GameId</i></td>
                <td><i>@item.GameState</i></td>
                <td><a class="btn btn-primary" asp-page-handler="EnterGame" asp-route-value="@item.GameId">Enter this game</a></td>
                <td><a class="btn btn-danger" asp-page-handler="RemoveGame" asp-route-value="@item.GameId">Remove</a></td>
            </tr>
        }
    </table>*@

Battleships/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
@using Microsoft.AspNetCore.Identity
@using Battleships.Models
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <img src="~/images/logo.png" class="center" />

    @if (SignInManager.IsSignedIn(User))
    {
        <div class="btn-group-vertical">
            <a class="btn btn-primary" asp-page-handler="StartGame" asp-route-size="5">Start Game (size 5×5)</a>
            <a class="btn btn-primary" asp-page-handler="StartGame" asp-route-size="10">Start Game (size 10×10)</a>
            <a class="btn btn-primary" asp-page="GamesListPH">List your games</a>
        </div>
    }
    else
    {

        <div class="jumbotron">
            <h2 class="display-4 text-center">Login required</h2>          
            <hr class="my-4">
            <div class="text-center">
                <a class="btn btn-secondary" style="margin-right: 30px" asp-area="Identity" asp-page="/Account/Login">Login</a>
                <a class="btn btn-light"  asp-area="Identity" asp-page="/Account/Register">Register</a>
            </div>
            
        </div>
    }



</body>
</html>